Implement support for decoding instructions with AVX-512 {sae}/{er}
DynamoRIO/dynamorio pull request #4605
Opened 2020-12-11 03:42 UTC by khuey

Instructions with {sae} overload the EVEX.b bit to mean suppress-all(-floating-point)-exceptions. Instructions with {er} (which requires {sae}) further overload the EVEX.L/LL bits to specify one of four static embedded rounding modes: {rn-sae}, {rd-sae}, {ru-sae}, {rz-sae} (round nearest, round down, round up, and round zero respectively). When {er} is supported that variant is limited to a single fixed width of registers, though not always ZMM (e.g. the various *SS/*SD instructions).

{sae} and {er} are applicable only to reg/reg forms of instructions. For instructions that support both broadcast forms and {sae} (both of which are controlled by EVEX.b=1) it is the modrm byte that chooses the meaning of EVEX.b (by choosing whether this is a reg/reg or reg/mem instruction). Instructions that support both grow a new entry in the MOD_EXT table to distinguish the two forms. Instructions that only support broadcast or {sae}/{er} use the appropriate slot in the EVEX_Wb_EXT table. Some mechanical support (allowing evex_Wb_extensions to contain MOD_EXT entries and allowing fixed width TYPE_H and TYPE_V entries) is also required.

There's no API for manipulating these flags in this patch. I've merely added decoding support for them. This is enough to decode the relevant instructions that are currently ifdefed out in the binutils tests, though enabling those tests also requires fixing #4566 which I haven't done here.

2020-12-27 02:43 UTC, derekbruening commented
@khuey -- this is ready for review, right?
@johnfxgalea -- was hoping you could take a look

2020-12-27 02:55 UTC, khuey commented
It is ready for review, though I imagine people have been busy with the holidays and whatnot.

2020-12-28 21:27 UTC, johnfxgalea requested changes
Thank you for your patience. I missed this request on my todo list.

W.R.T tests, I take it we will wait until we update those of binutils, right?

2020-12-28 21:42 UTC, khuey commented on core/ir/x86/decode.c
> +    /* can occur AFTER above checks (EVEX_W_EXT, in particular) */
I don't follow. Did you attach this comment to the wrong line?

2020-12-28 21:43 UTC, khuey commented on core/ir/x86/decode.c
> +            opsize == OPSZ_64;
No, they don't, because with embedded rounding control operands can be 64 bytes without having PREFIX_EVEX_LL set.

2020-12-28 21:45 UTC, khuey commented on core/ir/x86/decode.c
> +            *opnd = opnd_create_reg(decode_reg(DECODE_REG_VEX, di, optype, opsize));
The previous code handles both the presence and absence of PERFIX_VEX_L so why would we assert it?

2020-12-28 22:00 UTC, johnfxgalea commented on core/ir/x86/decode.c
> +    /* can occur AFTER above checks (EVEX_W_EXT, in particular) */
Oh, this is just a Nit. Just arrange comment's grammar. https://github.com/DynamoRIO/dynamorio/wiki/Code-Style#commenting-conventions

2020-12-28 22:06 UTC, khuey commented on core/ir/x86/decode.c
> +    /* can occur AFTER above checks (EVEX_W_EXT, in particular) */
Ah, well, ok, but this is literally copy and pasted from earlier blocks in this same function.

2020-12-28 22:10 UTC, johnfxgalea commented on core/ir/x86/decode.c
> +            *opnd = opnd_create_reg(decode_reg(DECODE_REG_VEX, di, optype, opsize));
Okay, I get you. I was just thinking of adding the assert to be defensive, but yeah, we can punt this.

2020-12-28 22:13 UTC, johnfxgalea commented on core/ir/x86/decode.c
> +    /* can occur AFTER above checks (EVEX_W_EXT, in particular) */
Yeah, at some point, we need to fix all of those. Generally, we try to have nice looking comments at least for new code.

2020-12-28 22:37 UTC, johnfxgalea commented on core/ir/x86/decode.c
> +            opsize == OPSZ_64;
Thank you for helping me understand. Can we add a comment here to help others better understand the code in the future?

Also, am I right to say that in this case, PREFIX_EVEX_b should be set? Do you think it is a good idea to add an check/assert for that here?

2020-12-28 22:47 UTC, khuey commented on core/ir/x86/decode.c
> +            opsize == OPSZ_64;
PREFIX_EVEX_b should be set in this case. There's not really any inherent obstacle in the encoding preventing Intel from introducing a 512 bit instruction that uses the L/LL bits for something else though without setting b, they just haven't.

2020-12-29 03:24 UTC, khuey commented on core/ir/x86/decode.c
> +            opsize == OPSZ_64;
I added a comment. I don't think an assertion is necessary.

2020-12-29 03:45 UTC, khuey commented
Comments addressed.

Pretty confident that those Windows failures aren't my fault.

2020-12-29 06:56 UTC, johnfxgalea approved these changes

2020-12-31 05:58 UTC, merged