Don't use libc's stderr in libdrdecode
DynamoRIO/dynamorio pull request #4651
Opened 2021-01-02 17:26 UTC by khuey

This fixes a regression introduced in #4567.

2021-01-02 17:42 UTC, khuey commented
Hrm, that fixes the Unix variant platforms but Windows requires something else apparently.

2021-01-03 18:02 UTC, derekbruening commented on core/ir/decodelib.c
> +    print_file(STDERR, "Usage error: %s (%s, line %d)\n", msg, file, line);
Not sure drdecode links utils.c which has print_file.  The `STDERR` should work b/c it turns into either `our_stderr` or `dr_get_stderr_handle` and both are defined up above in this file.  Probably this should be `s/print_file/fprintf/`?

2021-01-03 18:04 UTC, derekbruening commented on core/ir/decodelib.c
> +    print_file(STDERR, "Usage error: %s (%s, line %d)\n", msg, file, line);
Never mind, STDERR is the fileno and not the FILE*.  Plus, print_file is defined in this very file.

2021-01-03 18:04 UTC, derekbruening approved these changes

2021-01-03 18:07 UTC, derekbruening requested changes

2021-01-03 18:07 UTC, derekbruening commented on core/ir/decodelib.c
>  void
The commit title and description are not following the conventions in multiple respects:

+ The title should start with the issue number
+ The description should describe what is being fixed (yes, duplicating the title)
+ There should be a Fixes line at the bottom

Please see https://github.com/DynamoRIO/dynamorio/wiki/Code-Reviews#commit-messages

2021-01-03 20:17 UTC, khuey commented
Thanks for approving this I guess but I still don't know how to make it build on Windows :)

2021-01-03 20:28 UTC, derekbruening commented
Pasting the error would make it easier so we don't have to go click on the logs too.  Needs get_stderr_handle, etc. equivalent to the dr_ ones right?

2021-01-03 20:37 UTC, khuey commented
```
 ====> FAILURE in debug-internal-32 <====
debug-internal-32: **** 2 build errors ****
	drdecode.lib(decodelib.c.obj) : error LNK2019: unresolved external symbol _get_stderr_handle referenced in function _external_error
	clients\bin32\drdisas.exe : fatal error LNK1120: 1 unresolved externals
```

2021-01-03 20:37 UTC, khuey commented
I guess I could s/STDERR/dr_get_stderr_file()/ perhaps?

2021-01-03 20:38 UTC, derekbruening commented
globals_shared.h has `define STDERR (dr_get_stderr_file())` which is in decodelib.c, but globals.h (internal) has `#    define STDERR (file_t) get_stderr_handle()` which is not in decodelib.c -- maybe it needs both or an alias or whatnot?

2021-01-03 20:39 UTC, derekbruening commented
I would add get_stderr_handle which calls dr_get_stderr_handle or sthg

2021-01-03 21:00 UTC, derekbruening commented
> I guess I could s/STDERR/dr_get_stderr_file()/ perhaps?

Also seems good -- I guess the internal define is being used for decodelib itself and so there is no other reason for the non dr_ versions.  External users of the lib are going to have the external define and thus need the dr_ version.

2021-01-03 21:04 UTC, khuey commented
> 
> 
> > I guess I could s/STDERR/dr_get_stderr_file()/ perhaps?
> 
> Also seems good -- I guess the internal define is being used for decodelib itself and so there is no other reason for the non dr_ versions. External users of the lib are going to have the external define and thus need the dr_ version.

Doing this would require defining dr_get_stderr_file for the Unix platforms as its also windows only.

2021-01-04 02:58 UTC, khuey commented
Alright how about that?

2021-01-04 03:36 UTC, derekbruening approved these changes
Works for me.  Don't forget the commit title + description conventions.

2021-01-04 04:27 UTC, merged