i#2626: AArch64 v8 decode: Fix incorrect decode of ldrb
DynamoRIO/dynamorio pull request #5283
Opened 2022-01-14 17:19 UTC by joshua-warburton

This patch fixes two problems with ldrb:
 * Some variants were decoding to an x register
   when they should have been decoding to a w register
 * The "extension" LSL #0 was being decoded as uxtx #0

issues: #2626

2022-01-18 12:18 UTC, AssadHashmi requested changes

2022-01-18 12:18 UTC, AssadHashmi commented on core/ir/aarch64/codec.c
> +    case 0b011: extend = DR_EXTEND_UXTX; break; // Actually LSL
This comment is should be:
`// Alias for LSL. LSL preferred in disassembly.`

2022-01-18 16:16 UTC, AssadHashmi approved these changes

2022-01-18 16:52 UTC, merged

2022-05-23 14:51 UTC, petrochenkov commented
@joshua-warburton @derekbruening 
This change caused some regressions.

Not all places in DR are prepared to encounter a `w` register in a load index context.
For example, the register comparison with a stolen register in `drutil_insert_get_mem_addr_arm` can fail incorrectly now.

I'm not sure what other places besides `drutil_insert_get_mem_addr_arm` may be affected.

2022-05-24 14:47 UTC, petrochenkov commented
>What is the nature of the failure in release build? It gets the wrong address but silently?

Yes, by "comparison fails" I mean this branch is not reached
```c
        } else if (index == stolen) {
            index = replace_stolen_reg(drcontext, bb, where, memref, dst, scratch,
                                       scratch_used);
        }
```
since `w` registers are never identified as stolen.

It doesn't result in a crash, just silently results in incorrect instrumentation.
We noticed this pretty late by encountering "impossible" load addresses in traces written by instrumentation.

2022-05-24 14:59 UTC, petrochenkov commented
>could you file new issue in the tracker on this?

Done: https://github.com/DynamoRIO/dynamorio/issues/5498

2022-05-26 19:59 UTC, derekbruening commented
Trying to make it clear what the changes here involve: all issues with the scaling/extension of index registers are purely cosmetic; there were not problems with decoding and computing the scale/extension, just with the disassembly.
See also https://github.com/DynamoRIO/dynamorio/issues/5498#issuecomment-1138952432

So the only address computation bug was with the index being treated as X instead of W.