i#3044 AArch64 SVE codec: Add multi gpr memory load/stores
DynamoRIO/dynamorio pull request #5868
Opened 2023-02-13 16:20 UTC by joshua-warburton

This patch adds the appropriate macros, tests and codec entries to encode the following variants:
```
LD2B    { <Zt1>.B, <Zt2>.B }, <Pg>/Z, [<Xn|SP>, <Xm>]
LD3B    { <Zt1>.B, <Zt2>.B, <Zt3>.B }, <Pg>/Z, [<Xn|SP>, <Xm>]
LD4B    { <Zt1>.B, <Zt2>.B, <Zt3>.B, <Zt4>.B }, <Pg>/Z, [<Xn|SP>, <Xm>]
ST2B    { <Zt1>.B, <Zt2>.B }, <Pg>, [<Xn|SP>, <Xm>]
ST3B    { <Zt1>.B, <Zt2>.B, <Zt3>.B }, <Pg>, [<Xn|SP>, <Xm>]
ST4B    { <Zt1>.B, <Zt2>.B, <Zt3>.B, <Zt4>.B }, <Pg>, [<Xn|SP>, <Xm>]
```
issue: #3044

2023-02-13 17:53 UTC, AssadHashmi requested changes

2023-02-13 17:53 UTC, AssadHashmi commented on core/ir/opnd_api.h
> + * Creates a reg incremented  from an exiting \p opndby the \p increment value,
typo: existing
opndby all one word.

2023-02-13 17:53 UTC, AssadHashmi commented on core/ir/opnd_shared.c
> +#ifdef AARCH64
Looks like a significant chunk of this function, its main initialising code, is only compiled in for AArch64! Won't it fail for any architecture  other than AArch64? Currently none of the non-AArch64 regression tests call it, hence the full precommit pass.

As it's a fairly specific AArch64 SVE function it's probably best to `#ifdef` the whole function. Perhaps consider calling it `opnd_create_increment_sve_reg()` or something?

2023-02-14 14:01 UTC, AssadHashmi approved these changes

2023-02-14 16:38 UTC, joshua-warburton commented
Hey @derekbruening , merging seems to be broken. Do you know anything about the merge queue?

2023-02-14 16:41 UTC, derekbruening commented
We enabled the merge queue feature yesterday to avoid simultaneous commits having to update and re-run tests.  Don't know anything about it beyond the doc https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

2023-02-14 16:47 UTC, derekbruening commented
Is it this?
https://github.com/community/community/discussions/46757 
"make sure your Action workflow(s) are properly configured to trigger on merge_group event"

2023-02-14 16:57 UTC, joshua-warburton commented
Seems like it might be the issue- I can see no evidence it is actually triggering the jobs. It also doesn't seem to give us the ability to modify the commit message on merge.

2023-02-14 16:59 UTC, derekbruening commented
> It also doesn't seem to give us the ability to modify the commit message on merge.

Looks like we can now set it to use the PR title+desc -- maybe that is better in general as that can be reviewed prior to the squash:  https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/

I'm thinking it's worth trying these two things and if we still have problems we could then turn it off.  I will try them soon.

2023-02-14 17:03 UTC, joshua-warburton commented
slight weirdness for us is that we have to escape the instruction names in our pull requests otherwise we get:
LD2B    { <Zt1>.B, <Zt2>.B }, <Pg>/Z, [<Xn|SP>, <Xm>]
and I wonder how that's going to end up in the commit message.

2023-02-14 17:06 UTC, derekbruening commented
I disabled the merge queue for now -- does it let you merge this in the old way?

2023-02-14 18:34 UTC, derekbruening commented
I've turned on the default final message as the pull request title and description.  Let's see how that goes.

2023-02-14 19:45 UTC, merged