i#725 Re-expose the Windows detach in drconfig
DynamoRIO/dynamorio pull request #6205
Opened 2023-07-15 07:00 UTC by onroadmuwl

The old way to trigger detach on the Windows platform is the no-longer-supported "drcontrol" front-end. 
Re-exposing the detach feature in drconfig front-end on the Windows platform.

Fixes [#725](https://github.com/DynamoRIO/dynamorio/issues/725)

2023-07-17 21:04 UTC, derekbruening reviewed
This part looks fine.  What about testing?  We would like an automated test.  See e.g. client.attach_test which has support in multiple places to accomplish an attach from another process: see `git grep '<attach'`.  If you want to separate that out to a separate PR, since it is a little more complex than a regular test, that would be ok: in that case please add to the PR description here how you manually tested this.

2023-07-18 17:20 UTC, onroadmuwl commented on tools/drdeploy.c
>      "       Note that nudging 64-bit processes is not yet supported.\n"
Thanks, I have removed these codes

2023-07-18 17:21 UTC, onroadmuwl commented on tools/drdeploy.c
> +    "                         Detach to the process with the given pid.\n"
I have removed these codes following your suggestions.

2023-07-18 17:25 UTC, onroadmuwl commented
> This part looks fine. What about testing? We would like an automated test. See e.g. client.attach_test which has support in multiple places to accomplish an attach from another process: see `git grep '<attach'`. If you want to separate that out to a separate PR, since it is a little more complex than a regular test, that would be ok: in that case please add to the PR description here how you manually tested this.

I thought it would be clearer to submit the requests separately, so I described my manual testing approach in the PR description.

2023-07-18 18:32 UTC, derekbruening requested changes

2023-07-18 18:32 UTC, derekbruening commented on tools/drdeploy.c
>      "       Note that nudging 64-bit processes is not yet supported.\n"
I think there was some confusion: here I meant removing this old line (not added by your PR; it was already here) that says "Note that nudging 64-bit processes is not yet supported.\n".  I didn't mean to remove the -detach usage string: we want to add a -detach usage string.

2023-07-18 18:34 UTC, derekbruening commented on tools/drdeploy.c
>      "       Note that nudging 64-bit processes is not yet supported.\n"
The reason this is related to your PR is that detach uses a nudge underneath, so if this lack of 64-bit support were true, then detach wouldn't work on 64-bit either.

2023-07-18 22:36 UTC, onroadmuwl commented on tools/drdeploy.c
>      "       Note that nudging 64-bit processes is not yet supported.\n"
Sorry, I didn't understand your comment correctly before, and I have resubmitted the code.

2023-07-19 18:56 UTC, derekbruening approved these changes
LGTM.  I will merge this in.  Thank you for contributing this PR!

2023-07-19 18:59 UTC, derekbruening commented
FYI I changed it from "Fixes #725" to "Issue: #725" as we do want to get an automated test in place, and also we should update the documentation to include how to detach.  Once we have those 2 things we should be able to close #725.

2023-07-19 19:33 UTC, merged

2023-07-20 01:23 UTC, onroadmuwl commented
> FYI I changed it from "Fixes #725" to "Issue: #725" as we do want to get an automated test in place, and also we should update the documentation to include how to detach. Once we have those 2 things we should be able to close #725.

I will continue to accomplish both things.