i#5843 scheduler: Reduce default instr quantum to 500K
DynamoRIO/dynamorio pull request #6274
Opened 2023-08-18 21:45 UTC by derekbruening

Updates the default instruction count scheduling quantum to be smaller and consistent: 500K instructions instead of the 1M it was in the launcher and 10M in the scheduler.

Issue: #5843

2023-08-18 23:01 UTC, derekbruening commented
Actually I'm rethinking this one: let's discuss further offline.

2023-08-18 23:02 UTC, derekbruening commented
I can't figure out how to retract the review request -- so I marked as Draft.

2023-08-19 12:05 UTC, abhinav92003 approved these changes

2023-08-19 12:05 UTC, abhinav92003 commented on clients/drcachesim/scheduler/scheduler.h
> +        uint64_t quantum_duration = 500 * 1000;
So the other default is just for the launcher which would override this one, whereas this one is for any uses of scheduler_options_t?

2023-08-19 12:05 UTC, abhinav92003 commented on clients/drcachesim/scheduler/scheduler.h
> +        uint64_t quantum_duration = 500 * 1000;
Perhaps a quick note on why we think 500K is more appropriate (since we decided to switch from 1M to this, I assume there was a non-trivial reason).

2023-08-19 12:38 UTC, abhinav92003 requested changes

2023-08-19 12:38 UTC, abhinav92003 commented on clients/drcachesim/scheduler/scheduler.h
>           * specified by
> I can't figure out how to retract the review request -- so I marked as Draft.

Didn't see this before. Retracting the approval.

2023-08-21 19:23 UTC, derekbruening commented
I think with the blocking-syscall switch points the original 10M is reasonable; it could even be made a little higher (20M+ is more like it for 3GHz 10ms IPC a little below 1).  Abandoning this change.

2023-08-21 19:23 UTC, closed without merging