i#6451 AArch64: Fix large page support
DynamoRIO/dynamorio pull request #6868
Opened 2024-07-08 09:00 UTC by jackgallagher-arm

PR #5835 inadvertently broke support for large pages on AArch64 by introducing code that assumed a 4K page size.

The core options unit_tests were also failing on large page systems because a lot of options need to be overridden and the test was not accounting for extra options being set in the options string.

Issues: #1680, #6451
Fixes: #6451

2024-07-08 16:24 UTC, derekbruening commented
(OOO today; back tomorrow)

2024-07-09 18:56 UTC, derekbruening requested changes

2024-07-10 15:51 UTC, jackgallagher-arm commented on core/unix/os.c
> +     * on the stack. Align to page boundary, similar to that in get_clone_record().
I have moved all the login into get_clone_record().

2024-07-12 13:03 UTC, derekbruening approved these changes
(Sorry for delay; was out yesterday.)

2024-07-12 13:47 UTC, merged