i#5383: Fix macOS hello world on a64
DynamoRIO/dynamorio pull request #7170
Opened 2024-12-26 07:16 UTC by ndrewh

This fixes several build and runtime issues under macOS on ARM64 on macOS 14.4.1 (Sonoma)

- `FEATURE_PAUTH` is now detected on macOS using a sysctl
- In the preload library, `_init` needs `__attribute__((constructor))` to be run by dyld
- In the preload library, `dynamorio_set_envp` needs to be called before `get_application_short_name` can work (on macOS the application path is placed after envp)
- `PLATFORM_SUPPORTS_SCATTER_GATHER` is disabled on macOS
- Fixed sigcontext/mcontext conversion which assumes old `simd` size and was failing on an assert
- Fixed random compile issues under apple clang on ARM64
```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Known issues that remain:
- VM allocation frequently but nondeterministically fails reachability constraints. `-vm_size 500M` seems to fix this
- If you exit after fatal signal delivery, some bookkeeping asserts in `vmh_exit` are reached

The end result is that the `bbcount` tool works on a simple example program on macOS, in debug mode, without hitting any asserts:

```
bin64/drrun -debug -vm_size 500M -c api/bin/libbbcount.dylib -- ./main
```

2024-12-26 08:46 UTC, ndrewh commented
It appears I broke the x86 macOS tests, not sure what's going on there yet

2024-12-26 18:32 UTC, abhinav92003 commented
> It appears I broke the x86 macOS tests, not sure what's going on there yet

If it helps: check out the "Debugging Tests on Github Actions Runner" section at https://dynamorio.org/page_test_suite.html, which documents a way to ssh into the failing test machine.

2024-12-27 09:00 UTC, ndrewh commented
Alright somehow adding `IF_MACOS(__attribute__((constructor)))` to the `_init` function in preload.c is breaking the x86 tests. I can't say I understand the situation at all:

- on ARM64 macOS 14.4 the preload doesn't work at all without `__attribute__((constructor))`, which causes ~all of the client tests to fail
- on the x86 macOS runner (which is on macOS 13):
    - All of the tests seem to pass **_without_** the attribute (??? did dyld stop running `_init` in macOS 14? I searched https://github.com/apple-oss-distributions/dyld and i'm not seeing where they _ever_ ran `_init` -- maybe some compilers were automatically putting it in the appropriate section but recently changed this behavior)
    - Once you add the attribute some (but not all!) of the client tests fail with some seemingly random instrumentation assert.

2024-12-27 09:41 UTC, ndrewh commented
I don't think `api.startstop` fail is my fault, but I also don't see anything to suggest it's #6928

2025-01-03 07:23 UTC, edeiana requested changes
Add "Issue #5383" at the end of the PR description as suggested in the commit template.

(Thank you for contributing in making DynamoRIO work better on MacOS!)

2025-01-03 07:23 UTC, edeiana commented on core/unix/os_public.h
> +#if defined(MACOS) && defined(AARCH64)
Add an `XXX i#5383: ` comment explaining the error you observed when adding this attribute on x86 (like in your PR).

2025-01-03 07:23 UTC, edeiana commented on core/unix/signal_macos.c
> +        memcpy(&mc->simd[i], &fpc->__v[i], sizeof(fpc->__v[i]));
Add `ASSERT(sizeof(mc->simd[i]) == sizeof(fpc->__v[i]))` before this line.

2025-01-03 07:23 UTC, edeiana commented on core/unix/signal_macos.c
> +        memcpy(&fpc->__v[i], &mc->simd[i], sizeof(fpc->__v[i]));
Add `ASSERT(sizeof(mc->simd[i]) == sizeof(fpc->__v[i]))` before this line.

2025-01-03 07:23 UTC, edeiana commented on ext/drx/drx.c
> +#if (defined(X86) || defined(AARCH64)) && !(defined(MACOS) && defined(AARCH64))
Add an `XXX i#5383: ` comment specifying that PLATFORM_SUPPORTS_SCATTER_GATHER is still broken for MACOS in AARCH64.

2025-01-03 13:48 UTC, ndrewh commented on core/iox.h
> -                nbytes++;
Yeah at some point I was getting a clang error for this

2025-01-03 19:25 UTC, ndrewh commented on core/arch/aarch64/proc.c
> +            } else if (buflen == 4) {                                        \
I think it should work for all "integer" sysctls but I'm just guessing based on this documentation that they are all 4-byte (endianness matching host) integers https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/sysctl.3.html

I'll fix the name accordingly

2025-01-03 19:28 UTC, ndrewh commented on core/arch/aarch64/proc.c
> +            } else if (buflen == 4) {                                        \
Actually, I'll change it to something like this https://github.com/apple-oss-distributions/Security/blob/3dab46a11f45f2ffdbd70e2127cc5a8ce4a1f222/OSX/utilities/SecCoreAnalytics.m#L93-L99

2025-01-04 15:23 UTC, ndrewh commented on core/unix/signal_macos.c
> +        memcpy(&fpc->__v[i], &mc->simd[i], sizeof(fpc->__v[i]));
Oh uh these things aren't the same size since simd got enlarged. I think we have to zero it first then.

dr_simd_t is 512-bit on aarch64
__v is __uint128_t https://github.com/apple-oss-distributions/xnu/blob/8d741a5de7ff4191bf97d57b9f54c2f6d4a15585/osfmk/mach/arm/_structs.h#L573

2025-01-04 15:25 UTC, ndrewh commented on core/unix/signal_macos.c
> +        memcpy(&mc->simd[i], &fpc->__v[i], sizeof(fpc->__v[i]));
see below comment

2025-01-08 22:48 UTC, edeiana approved these changes

2025-01-08 22:48 UTC, edeiana commented on core/unix/signal_macos.c
> +        memcpy(&fpc->__v[i], &mc->simd[i], sizeof(fpc->__v[i]));
Thank you for your patience, we had a bit of a discussion internally about this.
If we are in the `ARM_NEON64` case, like this code assumes, we don't need to worry to zero the upper bits as they shouldn't be read anyway.
However, we need to check if that's the case.
This can be done as follows:
```
if (proc_has_feature(FEATURE_SVE)) {
     /* XXX i#5383: SVE and SVE2 support for MACOS still missing.
    */
    ASSERT_NOT_IMPLEMENTED(false);
} else {
    /* ARM_NEON64 case.
    */
    ASSERT((sizeof(mc->simd->q) * proc_num_simd_registers()) == sizeof(fpc->__v));
    for (int i = 0; i < proc_num_simd_registers(); i++)
        memcpy(&fpc->__v[i], &mc->simd[i].q, sizeof(fpc->__v[i]));
}
```

In the `sigcontext_to_mcontext_simd()` case use:
```
memcpy(&mc->simd[i].q, &fpc->__v[i], sizeof(mc->simd->q));
```

Please double check this actually works.

2025-01-08 22:48 UTC, edeiana commented on core/unix/signal_macos.c
> +        memcpy(&mc->simd[i], &fpc->__v[i], sizeof(fpc->__v[i]));
Use:
```
memcpy(&mc->simd[i].q, &fpc->__v[i], sizeof(mc->simd->q));
```
here.

2025-01-08 22:48 UTC, edeiana commented on core/arch/aarch64/proc.c
> + * XXX i#5383: Add remaining features from other sysctls
Add trailing ".".

2025-01-08 22:48 UTC, edeiana commented on ext/drx/drx.c
> +/* XXX i#5383: PLATFORM_SUPPORTS_SCATTER_GATHER is broken on aarch64 macOS */
Add trailing ".".

2025-01-10 19:16 UTC, edeiana commented on core/unix/signal_macos.c
> +        memcpy(&mc->simd[i].q, &fpc->__v[i], sizeof(mc->simd->q));
Please check if we are in the ARM_NEON64 case here as well (same way you're doing in `mcontext_to_sigcontext_simd()`).

2025-01-13 22:59 UTC, edeiana commented on core/unix/signal_macos.c
> +        ASSERT_NOT_IMPLEMENTED(false);
Thanks!

Btw, when you're ready, you can resolve all conversation, merge with master (resolve conflicts if necessary), wait for all tests to run, and finally "squash and merge" this PR yourself.

Thank you for contributing!

2025-01-15 15:17 UTC, ndrewh commented
@edeiana I don't have permissions to merge it myself, actually

2025-01-16 02:27 UTC, edeiana commented
You're right, apologies for the confusion, I'll merge this one then.
Thank you again for contributing!

2025-01-16 02:31 UTC, merged