i5383: Fix macOS arm64 test build/run
DynamoRIO/dynamorio pull request #7171
Opened 2024-12-27 06:06 UTC by ndrewh

This makes tests build and run properly on macOS (14.4) arm64 (M3). Many tests do not pass, but you can at least run them now.

- Disable selfmod tests due to build failures on M3
- Fix macOS build for mangle_pauth test (test still fails for some reason)
- Mark dump_ucontext as NYI on macOS

- Fixes NULL sigcontext_t in os_forge_exception
- Adds -vm_size 500M to client tests to avoid reachablity assert

2024-12-27 07:35 UTC, ndrewh commented
only a64 failure is raw-zlib https://github.com/DynamoRIO/dynamorio/issues/5635, doesn't seem to be my fault

2025-01-03 08:10 UTC, edeiana requested changes
Thank you for improving MacOS tests!

Please add "Issue #5383" at the bottom of your PR description.

2025-01-03 08:10 UTC, edeiana commented on core/unix/signal.c
> +    uc->IF_X64_ELSE(uc_mcontext64, uc_mcontext) = (void *)&frame->mc;
This seems weird.
`frame` is zeroed-out anyway, isn't this just changing `sc` to be a "different" NULL?
Also, shouldn't `sc` being NULL break more than MACOS?

2025-01-13 15:25 UTC, abhinav92003 commented on core/unix/signal.c
> +    uc->IF_X64_ELSE(uc_mcontext64, uc_mcontext) = (void *)&frame->mc;
> frame is zeroed-out anyway,

frame is indeed zeroed out; which means frame->uc.uc_mcontext is NULL before L7717.

> isn't this just changing sc to be a "different" NULL?

L7717 seems to set  frame->uc.uc_mcontext (which was NULL before) to &frame->mc; the address of mc within the frame is not NULL.

I'm not familiar with these Mac structs. I wonder if it is simply a requirement for frame->uc.uc_mcontext to point to frame->mc.

2025-01-13 15:27 UTC, abhinav92003 commented on core/unix/signal.c
> +    uc->IF_X64_ELSE(uc_mcontext64, uc_mcontext) = (void *)&frame->mc;
@ndrewh The comment at L7714 justifies that `uc->IF_X64_ELSE(uc_mcontext64, uc_mcontext)` must be set to something, but it doesn't explain why `&frame->mc` is the correct intended value. Can you add that reasoning to the comment?

2025-02-23 06:58 UTC, ndrewh commented on core/unix/signal.c
> +    uc->IF_X64_ELSE(uc_mcontext64, uc_mcontext) = (void *)&frame->mc;
> I'm not familiar with these Mac structs. I wonder if it is simply a requirement for frame->uc.uc_mcontext to point to frame->mc.

i am not an expert and the XNU code is a bit convoluted here but i think the answer is yes...

https://github.com/apple-oss-distributions/xnu/blob/8d741a5de7ff4191bf97d57b9f54c2f6d4a15585/bsd/dev/arm/unix_signal.c#L411

fixing comment

2025-02-23 07:39 UTC, ndrewh commented on suite/tests/CMakeLists.txt
> +  set(dr_test_ops -vm_size 500M ${dr_test_ops})
#7296 7296

2025-02-25 13:17 UTC, edeiana reviewed
Thank you for filing #7296 , please add it to the PR description along with #5883.

Have a look at https://github.com/DynamoRIO/dynamorio/issues/7296#issuecomment-2679125060. The rest LGTM.

2025-02-25 13:17 UTC, edeiana commented on suite/tests/CMakeLists.txt
> +  set(dr_test_ops -vm_size 500M ${dr_test_ops})
https://github.com/DynamoRIO/dynamorio/issues/7296#issuecomment-2679125060

As pointed out by Derek, this shouldn't be the cause for a fatal error.
What happens if you use `-no_vm_base_near_app`?

2025-02-25 15:53 UTC, ndrewh commented on suite/tests/CMakeLists.txt
> +  set(dr_test_ops -vm_size 500M ${dr_test_ops})
It turns out you can avoid the assert with `-no_reachable_client`. Is that a better temporary solution here? Presumably we eventually should fix #7296 so we can allocate >1GB near clients... 

https://github.com/DynamoRIO/dynamorio/issues/7296#issuecomment-2682457823

2025-02-25 18:17 UTC, derekbruening commented on suite/tests/CMakeLists.txt
> +  set(dr_test_ops -vm_size 500M ${dr_test_ops})
See https://github.com/DynamoRIO/dynamorio/issues/7296#issuecomment-2682906760: we should turn off -reachable_client on Mac and document that.

2025-02-28 01:35 UTC, edeiana approved these changes
LGTM, thank you for contributing!

2025-02-28 01:40 UTC, merged